### ISSUE TITLE
Allow string of hash for lookup_invoice

### ISSUE THREAD

**Issue by bitstein** [willcl-ark/lnd_grpc#2]
https://github.com/willcl-ark/lnd_grpc/blob/63fb095830e7e0115f0d94bcd3064ba52262aeed/lnd_grpc/lnd_grpc.py#L630-L639

Currently `lookup_invoice` requires you to use the bytes of `r_hash` as the parameter. It would be helpful to be able to just use the string of the hash as well, which is all that is needed on the command line.

**Comment by willcl-ark** [comment]
Hello @bitstein, I tend to agree with you here; the reason I went this route originally was because the return from list_invoices() was byte-format r_hashes, so I thought people might want to pipe between the two. It was easy enough though to just pass whichever kwargs are given though and the RPC server seems to accept either bytes or str: now in master (along with removing the huge docstrings and error catching decorators which were just making things ugly and messy)
